# configuration for master/CI branch
-
  branches:
    only:
      - master

  os: Visual Studio 2017
  configuration: AppVeyor
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '2.5.0.{build}'
    assembly_file_version: '2.5.0.{build}'
    assembly_informational_version: '2.5.0.{build}'
  environment:
    RestorePackages: false
  install:
    - cmd: choco install resharper-clt -y
    - cmd: choco install nvika -y
  before_build:
  - ps: .paket\paket.exe restore
  build:
    project: MaterialDesignToolkit.Wpf.sln
    verbosity: minimal
  after_build:
  - cmd: inspectcode --o="inspectcodereport.xml" -s=ERROR --projects:MaterialDesignColors* MaterialDesignToolkit.Wpf.sln
  - cmd: NVika parsereport "inspectcodereport.xml"
  - ps: nuget pack MaterialDesignThemes.nuspec -Version $env:APPVEYOR_BUILD_VERSION
  - ps: 7z a Demo.2.5.0.$env:APPVEYOR_BUILD_NUMBER.zip MainDemo.Wpf\bin\**\*.*
  artifacts:
  - path: '**\MaterialDesignThemes.*.nupkg'
  - path: Demo.*.zip

  version: 2.5.0-ci{build}

# configuration for release branch
-
  branches:
    only:
      - release

  os: Visual Studio 2017
  configuration: AppVeyor
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    RestorePackages: false
  install:
    - cmd: choco install resharper-clt -y
    - cmd: choco install nvika -y
  before_build:
  - ps: .paket\paket.exe restore
  build:
    project: MaterialDesignToolkit.Wpf.sln
    verbosity: minimal
  after_build:
  - cmd: inspectcode --o="inspectcodereport.xml" -s=ERROR --projects:MaterialDesignColors* MaterialDesignToolkit.Wpf.sln
  - cmd: NVika parsereport "inspectcodereport.xml"
  - ps: nuget pack MaterialDesignThemes.nuspec -Version $env:APPVEYOR_BUILD_VERSION
  - ps: 7z a Demo.$env:APPVEYOR_BUILD_VERSION.zip MainDemo.Wpf\bin\**\*.*
  artifacts:
  - path: '**\MaterialDesignThemes.*.nupkg'
  - path: Demo.*.zip

  version: 2.5.0.{build}
